; THIS FILE IS AUTOGENERATED !
; Please edit contents of '/macros/System/Calibration/Z Probe/Adjust pickup angle'
; Set Z-Probe servo angle
if exists(global.probePickAngle)
  set global.probePickAngle = 167
else
  global probePickAngle = 167
