; THIS FILE IS AUTOGENERATED !
; Please edit contents of '/macros/Save Z offset'
; Set Z probe trigger value, offset and trigger height
G31 P500 X0 Y28.50
G31 Z9.684

;When too Low => Subtract the difference
;When too High => Add the difference
