; THIS FILE IS AUTOGENERATED !
; Please edit contents of '/macros/Save Z offset'
; Set Z probe trigger value, offset and trigger height
G31 P500 X19.50 Y-23.00
G31 Z4.180

;When too Low => Subtract the difference
;When too High => Add the difference
