; THIS FILE IS AUTOGENERATED !
; Please edit contents of '/macros/Calibration/Offsets/XY Tool Alignment'
if exists(global.uoffset)
  set global.uoffset = -3.4328346
else
  global uoffset = -3.4328346
