; THIS FILE IS AUTOGENERATED !
; Please edit contents of '/macros/Calibration/Offsets/XY Tool Alignment'
if exists(global.yoffset)
  set global.yoffset = -0.5099506
else
  global yoffset = -0.5099506
